version: 0.2

phases:
 pre_build:
   commands:
     - echo Logging in to Amazon ECR...
     - aws ecr get-login-password | docker login --username AWS --password-stdin 864840124913.dkr.ecr.ap-northeast-1.amazonaws.com
 build:
   commands:
     - echo Build started on `date`
     - echo Building the Docker image...
     - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
     - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 864840124913.dkr.ecr.ap-northeast-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
 post_build:
   commands:
     - echo Build completed on `date`
     - echo Pushing the Docker image...
     - docker push 864840124913.dkr.ecr.ap-northeast-1.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
